import Foundation

enum TrainingCatalog {
    static let all: [TrainingDefinition] = make()
    /// Hry viditelné v tréninku. Další se přidávají sem.
    static let showcase = [
        "around-clock", "bobs-27", "shanghai", "checkout-40", "treble-20", "practice-501"
    ]
    static var showcaseGames: [TrainingDefinition] { showcase.compactMap(find) }
    static func find(_ id: String) -> TrainingDefinition? { all.first { $0.id == id } }

    private static func make() -> [TrainingDefinition] {
        var items: [TrainingDefinition] = []
        func add(_ number: Int, _ id: String, _ title: String, _ summary: String, _ rules: String, _ category: TrainingCategory, _ minutes: Int, _ listed: TrainingLevel, _ kind: TrainingKind, options: TrainingOptions = TrainingOptions()) {
            items.append(TrainingDefinition(id: id, number: number, title: title, summary: summary, rules: rules, category: category, minutes: minutes, listed: listed, options: options, kind: kind))
        }
        let darts = TrainingOptions(darts: true, accuracy: true)
        let rounds = TrainingOptions(rounds: true)
        let checkout = TrainingOptions(checkouts: true)
        let lives = TrainingOptions(lives: true)
        let segments = TrainingOptions(darts: true, segments: true, accuracy: true)
        let multi = TrainingOptions(rounds: true, multiplayer: true)
        add(1, "around-clock", "Around the Clock", "Postupně tref 1 až 20.", "Zásah libovolným násobičem posouvá na další číslo. Minutí zůstává.", .accuracy, 8, .beginner, .around(mult: nil, bull: false, limit: 80), options: TrainingOptions(darts: true))
        add(2, "around-clock-doubles", "Around the Clock Doubles", "Postupně D1 až D20.", "Počítá se jen double daného čísla.", .doubles, 12, .advanced, .around(mult: 2, bull: false, limit: 120), options: TrainingOptions(darts: true))
        add(3, "around-clock-triples", "Around the Clock Triples", "Postupně T1 až T20.", "Počítá se jen triple daného čísla.", .doubles, 12, .pro, .around(mult: 3, bull: false, limit: 120), options: TrainingOptions(darts: true))
        add(4, "around-clock-bull", "Around the Clock Bull", "Čísla 1–20 a nakonec bull.", "Po dvacítce uzavře bull 25 nebo 50.", .accuracy, 10, .advanced, .around(mult: nil, bull: true, limit: 90), options: TrainingOptions(darts: true))
        add(5, "bobs-27", "Bob's 27", "Klasický trénink doublů od 27 bodů.", "Start 27. Zásah D1–D20 přičte hodnotu doublu, tři minuly ji odečtou. Nula a méně je konec.", .doubles, 15, .advanced, .bobs27)
        add(6, "jdc", "JDC Challenge", "Academy karta doublů, čísel a bullu.", "Deset cílů po třech šipkách: double, 15, double, 16, double, 17, 18, 19, 20, bull. Body jen za zadaný cíl.", .accuracy, 8, .advanced, .jdc)
        add(7, "darts-100-20", "100 Darts at 20", "Sto šipek na segment 20.", "Počítá se každý násobič dvacítky. Úspěch je dosažená úspěšnost.", .accuracy, 12, .beginner, .volume(aim: .segment(20, nil), darts: 100, accuracy: 0.4), options: darts)
        add(8, "darts-100-bull", "100 Darts at Bull", "Sto šipek na bull.", "Platí 25 i 50.", .accuracy, 12, .advanced, .volume(aim: .bull, darts: 100, accuracy: 0.25), options: darts)
        add(9, "darts-100-doubles", "100 Darts at Doubles", "Sto šipek na libovolný double.", "Single ani triple se nepočítají.", .doubles, 12, .advanced, .volume(aim: .anyDouble, darts: 100, accuracy: 0.2), options: darts)
        add(10, "darts-100-triples", "100 Darts at Triples", "Sto šipek na libovolný triple.", "Počítá se jen triple 1–20.", .doubles, 12, .pro, .volume(aim: .anyTriple, darts: 100, accuracy: 0.15), options: darts)
        add(11, "shanghai", "Shanghai", "Čísla 1–7, single, double a triple.", "Tři šipky na číslo kola. Single, double i triple v jedné návštěvě je okamžitá výhra.", .accuracy, 8, .advanced, .shanghai(numbers: Array(1...7), instant: true, limit: 21))
        add(12, "shanghai-20", "Shanghai 20", "Na dvacítce seber všechny násobiče.", "V limitu šipek tref S20, D20 a T20. Jedna návštěva hru neukončí.", .accuracy, 5, .advanced, .shanghai(numbers: [20], instant: false, limit: 12), options: TrainingOptions(darts: true))
        add(13, "halve-it", "Halve-It", "Cíle 20–15, double, triple a bull.", "Tři minuty na cíli půlí skóre. Zásah přičítá body segmentu.", .scoring, 8, .beginner, .halve)
        add(14, "cricket-practice", "Cricket Practice", "Zavři 15–20 a bull.", "Tři marky zavřou číslo. Triple zavře prázdné číslo najednou. Bez soupeře.", .accuracy, 8, .beginner, .cricket(numbers: [20, 19, 18, 17, 16, 15, 25], limit: 45), options: TrainingOptions(darts: true))
        add(15, "mickey-mouse", "Mickey Mouse", "Krátký cricket na 20, 19 a 18.", "Stejná tři marky, jen tři čísla.", .accuracy, 5, .beginner, .cricket(numbers: [20, 19, 18], limit: 24))
        add(16, "treble-20", "Treble 20 Challenge", "Série na T20.", "Počítá se jen triple 20, ne libovolných 60 bodů.", .doubles, 6, .advanced, .volume(aim: .segment(20, 3), darts: 30, accuracy: 0.25), options: darts)
        add(17, "treble-19", "Treble 19 Challenge", "Série na T19.", "Počítá se jen triple 19.", .doubles, 6, .advanced, .volume(aim: .segment(19, 3), darts: 30, accuracy: 0.25), options: darts)
        add(18, "bull-challenge", "Bull Challenge", "Zásahy 25 a 50.", "Krátká bull série s danou úspěšností.", .accuracy, 6, .advanced, .volume(aim: .bull, darts: 30, accuracy: 0.3), options: darts)
        add(19, "doubles-practice", "Doubles Practice", "Vybrané doubly po třech šipkách.", "Výchozí jsou D20, D16, D8, D4 a D10. Segmenty si můžeš změnit.", .doubles, 8, .beginner, .segments(pick: .list([20, 16, 8, 4, 10]), mult: 2, darts: 3, accuracy: 0.4), options: segments)
        add(20, "singles-accuracy", "Singles Accuracy", "Přesnost jednotlivých čísel.", "Dva singly na každé číslo 1–20.", .accuracy, 8, .beginner, .segments(pick: .singles, mult: 1, darts: 2, accuracy: 0.5), options: segments)
        add(21, "checkout-121", "121 Checkout", "Zavři 121.", "Double out. Přehoz vrací skóre návštěvy. Málo kol znamená neúspěch.", .checkout, 6, .advanced, .checkoutUntil(start: 121, visits: 6, doubleIn: false), options: checkout)
        add(22, "checkout-170", "170 Checkout", "Nejvyšší zavření třemi šipkami.", "T20, T20 a bull. Jiná sestava, která dá přesně 170 doublem, platí taky.", .checkout, 3, .pro, .checkoutFixed(leaves: [170], visits: 1, need: 1, doubleIn: false), options: checkout)
        add(23, "checkout-40", "40 Checkout", "Jedna návštěva na 40.", "Nejčistší cesta je D20.", .checkout, 3, .beginner, .checkoutFixed(leaves: [40], visits: 1, need: 1, doubleIn: false), options: checkout)
        add(24, "checkout-32", "32 Checkout", "Jedna návštěva na 32.", "Nejčistší cesta je D16.", .checkout, 3, .beginner, .checkoutFixed(leaves: [32], visits: 1, need: 1, doubleIn: false), options: checkout)
        add(25, "checkout-61-100", "61–100 Checkout", "Série zavření mezi 61 a 100.", "Každé skóre má jednu návštěvu. Nezavřitelná čísla se do zadání nedostanou.", .checkout, 8, .advanced, .checkoutRange(low: 61, high: 100, count: 8, need: 3), options: rounds)
        add(26, "checkout-101-170", "101–170 Checkout", "Delší zavření až po 170.", "Jedna návštěva na každé vylosované skóre.", .checkout, 8, .pro, .checkoutRange(low: 101, high: 170, count: 6, need: 2), options: rounds)
        add(27, "checkout-random", "Random Checkout", "Náhodná zavřitelná skóre.", "Losování je uložené v semínku hry, takže opakování hodů dopadne stejně.", .checkout, 8, .advanced, .checkoutRange(low: 2, high: 170, count: 8, need: 3), options: rounds)
        add(28, "checkout-ladder", "Checkout Ladder", "Žebřík od 40 po 170.", "Postup 40, 60, 80, 100, 120, 140, 160 a 170.", .checkout, 10, .advanced, .checkoutGenerated(mode: "ladder", need: 5))
        add(29, "checkout-countdown", "Checkout Countdown", "Sestup od 170 po desítkách.", "170, 160, 150 a dál až po 40.", .checkout, 10, .advanced, .checkoutGenerated(mode: "countdown", need: 5))
        add(30, "double-trouble", "Double Trouble", "Všechny doubly včetně bullu.", "Jedna návštěva na D1–D20 a bull.", .doubles, 10, .advanced, .checkoutGenerated(mode: "doubles", need: 8))
        add(31, "double-in", "Double In Practice", "Nejdřív se otevři doublem.", "Ze 81 se hraje double in a double out.", .checkout, 6, .advanced, .checkoutUntil(start: 81, visits: 6, doubleIn: true), options: checkout)
        add(32, "double-in-out", "Double In / Double Out", "Celý malý leg od 121.", "Bez otevíracího doublu se body nepočítají a zavírá se zase doublem.", .checkout, 8, .advanced, .checkoutUntil(start: 121, visits: 8, doubleIn: true), options: checkout)
        add(33, "finish-3", "Finish in 3", "Čtyři zavření na jednu návštěvu.", "121, 100, 80 a 60. Splnit stačí daný počet.", .checkout, 6, .advanced, .checkoutFixed(leaves: [121, 100, 80, 60], visits: 1, need: 2, doubleIn: false))
        add(34, "finish-6", "Finish in 6", "Na každé skóre jsou dvě návštěvy.", "160, 140, 130 a 120. Checkout může přijít i dřív.", .checkout, 8, .pro, .checkoutFixed(leaves: [160, 140, 130, 120], visits: 2, need: 2, doubleIn: false))
        add(35, "checkout-1-100", "Checkout 1–100", "Všechna zavřitelná skóre do 100.", "1 a ostatní nezavřitelná čísla hra přeskočí a ukáže je zvlášť.", .checkout, 20, .advanced, .checkoutGenerated(mode: "to100", need: 20))
        add(36, "practice-301", "301 Practice", "Celý leg 301, double out.", "Sleduje se průměr, návštěvy a checkout.", .scoring, 8, .beginner, .x01(start: 301, limit: 90, doubleIn: false, minAverage: nil), options: checkout)
        add(37, "practice-501", "501 Practice", "Celý leg 501, double out.", "Klasická délka zápasu v sólo tréninku.", .scoring, 10, .advanced, .x01(start: 501, limit: 99, doubleIn: false, minAverage: nil), options: checkout)
        add(38, "practice-701", "701 Practice", "Dlouhý leg 701.", "Víc šipek na průměr a výdrž.", .scoring, 15, .advanced, .x01(start: 701, limit: 150, doubleIn: false, minAverage: nil), options: checkout)
        add(39, "endurance-1001", "1001 Endurance", "Tisíc bodů na jedno zavření.", "Dlouhý leg bez změny pravidel double out.", .endurance, 20, .pro, .x01(start: 1001, limit: 240, doubleIn: false, minAverage: nil), options: checkout)
        add(40, "challenge-9", "9 Dart Challenge", "501 na devět šipek.", "Limit je součást hry a obtížnost ho nezkracuje.", .scoring, 3, .pro, .x01(start: 501, limit: 9, doubleIn: false, minAverage: nil), options: checkout)
        add(41, "challenge-15", "15 Dart Challenge", "501 na patnáct šipek.", "Zavření po limitu se nepočítá.", .scoring, 4, .pro, .x01(start: 501, limit: 15, doubleIn: false, minAverage: nil), options: checkout)
        add(42, "challenge-30", "30 Dart Challenge", "501 na třicet šipek.", "Pohodlnější limit než devítka, pořád double out.", .scoring, 6, .advanced, .x01(start: 501, limit: 30, doubleIn: false, minAverage: nil), options: checkout)
        add(43, "challenge-60", "60 Dart Challenge", "501 na šedesát šipek.", "Prostor na pomalejší stavbu a čistý checkout.", .scoring, 8, .beginner, .x01(start: 501, limit: 60, doubleIn: false, minAverage: nil), options: checkout)
        add(44, "challenge-180", "180 Challenge", "Kolik maxim padne v sérii návštěv.", "180 jsou jen tři trojité dvacítky, ne jiný součet.", .scoring, 6, .pro, .visitGoal(atLeast: nil, exact: 180, count: 10, need: 1), options: multi)
        add(45, "ton", "Ton Challenge", "Návštěvy 100 a víc.", "Počítá se součet tří skutečných segmentů.", .scoring, 6, .beginner, .visitGoal(atLeast: 100, exact: nil, count: 10, need: 4), options: multi)
        add(46, "ton-40", "Ton 40 Challenge", "Návštěvy 140 a víc.", "140, 180 i cokoliv mezi tím.", .scoring, 6, .advanced, .visitGoal(atLeast: 140, exact: nil, count: 10, need: 2), options: multi)
        add(47, "scoring-ladder", "Scoring Ladder", "Návštěvy 40, 60, 80, 100, 140 a 180.", "Slabší návštěva žebřík ukončí.", .scoring, 6, .advanced, .ladder(targets: [40, 60, 80, 100, 140, 180]))
        add(48, "consistency", "Consistency Challenge", "Stabilní návštěvy bez výkyvu.", "Úspěch chce malý rozptyl a zároveň slušný průměr, ne sérii nul.", .endurance, 6, .advanced, .consistency(visits: 8, spread: 40, floor: 45), options: rounds)
        add(49, "high-score", "High Score", "Nejvyšší součet za daný počet kol.", "Vyšší skóre je lepší. Druhý hráč se střídá po návštěvách.", .scoring, 6, .beginner, .highScore(visits: 8), options: multi)
        add(50, "average-builder", "Average Builder", "Drž třišipkový průměr nad cílem.", "Cíl se mění s obtížností.", .scoring, 8, .advanced, .average(visits: 8, target: 60), options: TrainingOptions(rounds: true, target: true))
        add(51, "sniper", "Dartiqo Sniper", "Přesný segment včetně násobiče.", "Kombo roste jen při zásahu. T20 není totéž co S20.", .original, 5, .advanced, .sniper(rounds: 12, need: 6), options: rounds)
        add(52, "double-hunter", "Double Hunter", "Lov náhodných doublů na životy.", "Tři šipky na double. Minutí všech tří bere život.", .doubles, 6, .advanced, .hunter(rounds: 8, lives: 3), options: lives)
        add(53, "boss", "Dartiqo Boss Fight", "Tři bossové, každý padá na šipkařských úkolech.", "Zásah nebo checkout bere 34 HP. Tři selhání navíc berou život.", .original, 8, .pro, .boss(lives: 3), options: lives)
        add(54, "pressure", "Pressure Master", "Krátké zavření pod tlakem.", "40, 32, 50, 24 a 16, každé na jednu návštěvu.", .original, 5, .advanced, .checkoutFixed(leaves: [40, 32, 50, 24, 16], visits: 1, need: 3, doubleIn: false))
        add(55, "survivor", "Dartiqo Survivor", "Cíle se postupně ztěžují.", "Single, double, triple a nakonec bull. Minutí bere život a cíl zůstává.", .endurance, 6, .advanced, .survivor(steps: 12, lives: 3), options: lives)
        add(56, "streak", "Perfect Streak", "Nejdelší série bez minutí.", "První chyba hru ukončí.", .original, 4, .advanced, .streak(aim: .segment(20, 3), need: 5, limit: 30), options: TrainingOptions(darts: true))
        add(57, "triple-switch", "Triple Switch", "Po každé šipce jiný triple.", "Pořadí je uložené v zadání hry.", .doubles, 5, .pro, .switchTreble(darts: 15, need: 6), options: TrainingOptions(darts: true))
        add(58, "double-roulette", "Double Roulette", "Každou návštěvu jiný double.", "Stačí jeden zásah ze tří šipek.", .doubles, 6, .advanced, .roulette(visits: 8, need: 4), options: rounds)
        add(59, "bull-or-nothing", "Bull or Nothing", "Body jen z bullu, kombo je násobí.", "Minutí vynuluje kombo. Single ani číslo body nedá.", .original, 5, .advanced, .bullScore(darts: 12, target: 150), options: TrainingOptions(darts: true, target: true))
        add(60, "combo", "Dartiqo Combo", "Vzor S20, D20, T20 a bull.", "Chyba vrací vzor na začátek. Tři dokončené vzory vyhrávají.", .original, 5, .advanced, .combo(need: 3, limit: 36))
        add(61, "sudden-death", "Sudden Death", "První chyba končí výzvu.", "Ve dvou hráčích se střídá po šipce.", .original, 4, .advanced, .sudden(need: 5, limit: 20), options: TrainingOptions(darts: true, multiplayer: true))
        add(62, "puzzle", "3 Dart Puzzle", "Odehraj navržený checkout.", "Platí i jiná legální cesta na stejné skóre. Přehoz kolo neuzavře.", .checkout, 6, .advanced, .puzzle(count: 5, need: 3), options: rounds)
        add(63, "rush", "Target Rush", "Co nejvíc cílů, než vyprší čas.", "Konec přijde s časem nebo po limitu šipek.", .original, 2, .beginner, .rush(seconds: 60, need: 8, limit: 40), options: TrainingOptions(darts: true, time: true))
        add(64, "marathon", "Dartiqo Marathon", "Dvacet různých úkolů za sebou.", "Na každý jsou tři šipky. Tři minuty úkol ukončí celý maraton.", .endurance, 15, .advanced, .marathon(tasks: 20, limit: 60))
        add(65, "risk", "Risk or Reward", "Před návštěvou volíš jistotu, nebo T20.", "Jistota platí S20. Risk dá 180 jen za tři T20, jinak nulu.", .original, 5, .advanced, .risk(rounds: 6, target: 120), options: rounds)
        add(66, "chaos", "Around the Chaos", "Čísla 1–20 v náhodném pořadí.", "Pořadí je součást uloženého zadání.", .accuracy, 8, .advanced, .chaos(limit: 80), options: TrainingOptions(darts: true))
        add(67, "no-favorite", "No Favorite", "Čísla, která házíš nejmíň.", "Bez historie přijde pevná diagnostická sada.", .adaptive, 6, .beginner, .segments(pick: .rare, mult: nil, darts: 3, accuracy: 0.4), options: segments)
        add(68, "weak-spot", "Weak Spot Killer", "Trénink podle skutečných slabin.", "Málo dat znamená diagnostiku T20, D16, 20 a bull.", .adaptive, 8, .advanced, .segments(pick: .weak, mult: nil, darts: 8, accuracy: 0.35), options: segments)
        add(69, "perfect-60", "Perfect 60", "Přesně 60 třemi šipkami.", "Jedna T20 hru nesplní. Počítá se součet tří segmentů.", .scoring, 5, .beginner, .perfect(visits: 8, need: 3, total: 60), options: rounds)
        add(70, "exact-score", "Exact Score", "Náhodný přesný součet tří šipek.", "Cíl i jedna z cest jsou uložené v zadání.", .original, 5, .advanced, .exact(rounds: 8, need: 4), options: rounds)
        add(71, "memory", "Dartiqo Memory", "Zapamatuj si pořadí a odehraj ho.", "Jedna jiná šipka výzvu ukončí.", .original, 4, .beginner, .memory(length: 4), options: rounds)
        add(72, "escape", "Checkout Escape", "Pět místností, v každé checkout.", "Selhání bere život. Názvy místností jsou jen téma, pravidlo je zavření.", .original, 8, .advanced, .escape(rooms: 5, lives: 3), options: lives)
        add(73, "tower", "Dartiqo Tower", "Osm pater se stoupající obtížností.", "Patro chce zásah do tří šipek. Tři minuty věž končí.", .original, 8, .pro, .tower(floors: 8))
        add(74, "one-dart", "One Dart Hero", "Na každý cíl jen jedna šipka.", "Úspěch je daný počet zásahů, ne bezchybná série.", .original, 4, .advanced, .oneDart(rounds: 10, need: 5), options: rounds)
        add(75, "ghost", "Rival Ghost", "Součet proti uloženému průběhu.", "Bez historie se první dohraná hra stane ghostem. Není to simulovaný soupeř.", .original, 6, .advanced, .ghost(visits: 8), options: TrainingOptions(rounds: true, ghost: true))
        add(76, "adaptive-501", "Adaptive 501", "501 s cílovým průměrem.", "Zavření pod požadovaným průměrem nestačí.", .adaptive, 10, .advanced, .x01(start: 501, limit: 99, doubleIn: false, minAverage: 50), options: TrainingOptions(target: true, checkouts: true))
        add(77, "comeback", "Comeback King", "301 a soupeř, který zavírá za pevný počet kol.", "Soupeř nehází skutečné šipky. Je to skript: zavře, když jeho kola dojdou.", .original, 6, .advanced, .comeback(opponentVisits: 3))
        add(78, "final-dart", "Final Dart", "Úkol plní jen třetí šipka návštěvy.", "První dvě se do cíle nepočítají.", .original, 5, .advanced, .finalDart(visits: 8, need: 4), options: rounds)
        add(79, "daily-9", "Dartiqo Daily 9", "Devět cílů podle dne.", "Stejné semínko dne vrátí stejnou devítku.", .daily, 8, .advanced, .daily(tasks: 9))
        add(80, "world-tour", "World Tour", "Osm zastávek a v každé jiný úkol.", "Tři minuty na zastávce končí turné.", .original, 12, .advanced, .world(stops: 8))
        return items
    }
}
